name: Build And Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run build script
        env:
          HY_APP_PLATFORMS: 'darwin/amd64,darwin/amd64-avx,darwin/arm64,windows/amd64,windows/amd64-avx,windows/386,windows/arm64,linux/amd64,linux/amd64-avx,linux/386,linux/arm,linux/armv5,linux/arm64,linux/s390x,linux/mipsle,linux/mipsle-sf,freebsd/amd64,freebsd/amd64-avx,freebsd/386,freebsd/arm,freebsd/arm64'
        run: chmod 777 ./build.sh && ./build.sh
        shell: bash

      - name: Generate hashes
        run: |
          cd build
          for f in $(find . -type f); do
            sha256sum $f | sudo tee -a hashes.txt
          done

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/NeverIdle-darwin-amd64
            ./build/NeverIdle-darwin-amd64-avx
            ./build/NeverIdle-darwin-arm64
            ./build/NeverIdle-windows-amd64.exe
            ./build/NeverIdle-windows-amd64-avx.exe
            ./build/NeverIdle-windows-386.exe
            ./build/NeverIdle-windows-arm64.exe
            ./build/NeverIdle-linux-amd64
            ./build/NeverIdle-linux-amd64-avx
            ./build/NeverIdle-linux-386
            ./build/NeverIdle-linux-arm
            ./build/NeverIdle-linux-armv5
            ./build/NeverIdle-linux-arm64
            ./build/NeverIdle-linux-s390x
            ./build/NeverIdle-linux-mipsle
            ./build/NeverIdle-linux-mipsle-sf
            ./build/NeverIdle-freebsd-amd64
            ./build/NeverIdle-freebsd-amd64-avx
            ./build/NeverIdle-freebsd-386
            ./build/NeverIdle-freebsd-arm
            ./build/NeverIdle-freebsd-arm64
            ./build/hashes.txt
